/*
 * JFrameGame.java
 *
 * Created on 20/07/2009, 01:18:48 PM
 */
package michi.view;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author cesar.diaz
 */
public class JFrameGame extends javax.swing.JFrame implements ActionListener {

    private int counter = 0, v = 0;
    private String matrix[][], s;

    /**
     * Creates new form JFrameMain
     */
    public JFrameGame() {
        initComponents();

        matrix = new String[3][3];
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[i].length; j++) {
                matrix[i][j] = new String(i + "" + j);
            }
        }
        button00.addActionListener(this);
        button01.addActionListener(this);
        button02.addActionListener(this);
        button10.addActionListener(this);
        button11.addActionListener(this);
        button12.addActionListener(this);
        button20.addActionListener(this);
        button21.addActionListener(this);
        button22.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        button00 = new javax.swing.JButton();
        button01 = new javax.swing.JButton();
        button02 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        button21 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuGame = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuIAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("michi/view/Bundle"); // NOI18N
        setTitle(bundle.getString("app.title")); // NOI18N

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setLayout(new java.awt.GridLayout(3, 3));

        button00.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button00);

        button01.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button01);

        button02.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button02);

        button10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button10);

        button11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button11);

        button12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button12);

        button20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button20);

        button21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button21);

        button22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panel.add(button22);

        menuGame.setText(bundle.getString("dict.game")); // NOI18N

        menuItemNew.setText(bundle.getString("dict.new")); // NOI18N
        menuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewActionPerformed(evt);
            }
        });
        menuGame.add(menuItemNew);

        menuBar.add(menuGame);

        menuHelp.setText(bundle.getString("dict.help")); // NOI18N

        jMenuIAbout.setText(bundle.getString("dict.about")); // NOI18N
        menuHelp.add(jMenuIAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        matrix = new String[3][3];
        v = counter = 0;
        modificarPanel(1);
    }//GEN-LAST:event_menuItemNewActionPerformed

    private boolean ganador() {
        boolean b = false;
        if (counter >= 3) {
            for (int i = 0; i < matrix.length && !b; i++) {
                if (matrix[i][0].equals(matrix[i][1]) && matrix[i][1].equals(matrix[i][2])) {
                    b = true;
                    v = 1;
                    s = matrix[i][0];
                }
                if (matrix[0][i].equals(matrix[1][i]) && matrix[1][i].equals(matrix[2][i])) {
                    b = true;
                    v = 1;
                    s = matrix[0][i];
                }
                if (i == 0) {
                    if (matrix[i][i].equals(matrix[i + 1][i + 1]) && matrix[i + 1][i + 1].equals(matrix[i + 2][i + 2])) {
                        b = true;
                        v = 1;
                        s = matrix[i][i];
                    }
                } else if (i == 2) {
                    if (matrix[0][i].equals(matrix[i - 1][i - 1]) && matrix[i - 1][i - 1].equals(matrix[i][0])) {
                        b = true;
                        v = 1;
                        s = matrix[i][i];
                    }
                }
            }
        }
        return b;
    }

    private void modificarPanel(int tipo) {
        Component[] cs = panel.getComponents();
        for (int i = 0; i < cs.length; i++) {
            switch (tipo) {
                case 0:
                    cs[i].setEnabled(false);
                    break;
                case 1:
                    cs[i].setEnabled(true);
                    ((javax.swing.JButton) cs[i]).setText("");
                    break;
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton btn = (JButton) e.getSource();
        String str = "";
        if (counter % 2 == 0) {
            str = "X";
        } else {
            str = "O";
        }
        btn.setText(str);
        btn.setEnabled(false);
        counter++;
        if (e.getSource().equals(button00)) {
            matrix[0][0] = str;
        }
        if (e.getSource().equals(button01)) {
            matrix[0][1] = str;
        }
        if (e.getSource().equals(button02)) {
            matrix[0][2] = str;
        }
        if (e.getSource().equals(button10)) {
            matrix[1][0] = str;
        }
        if (e.getSource().equals(button11)) {
            matrix[1][1] = str;
        }
        if (e.getSource().equals(button12)) {
            matrix[1][2] = str;
        }
        if (e.getSource().equals(button20)) {
            matrix[2][0] = str;
        }
        if (e.getSource().equals(button21)) {
            matrix[2][1] = str;
        }
        if (e.getSource().equals(button22)) {
            matrix[2][2] = str;
        }
        if (ganador() && v == 1) {
            JOptionPane.showMessageDialog(this, "Ganador: " + s, getTitle(), JOptionPane.INFORMATION_MESSAGE);
            modificarPanel(0);
        } else if (counter == 9) {
            JOptionPane.showMessageDialog(this, "No hay Ganador", getTitle(), JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button00;
    private javax.swing.JButton button01;
    private javax.swing.JButton button02;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button20;
    private javax.swing.JButton button21;
    private javax.swing.JButton button22;
    private javax.swing.JMenuItem jMenuIAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGame;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
