/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameMain.java
 *
 * Created on 20/07/2009, 01:18:48 PM
 */
package michi;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author cesardl
 */
public class JFrameMain extends javax.swing.JFrame implements ActionListener {

    private int cont = 0,  v = 0;
    private String matriz[][],  s;

    /** Creates new form JFrameMain */
    public JFrameMain() {
        initComponents();

        matriz = new String[3][3];
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[i].length; j++) {
                matriz[i][j] = new String(i + "" + j);
            }
        }
        jButton00.addActionListener(this);
        jButton01.addActionListener(this);
        jButton02.addActionListener(this);
        jButton10.addActionListener(this);
        jButton11.addActionListener(this);
        jButton12.addActionListener(this);
        jButton20.addActionListener(this);
        jButton21.addActionListener(this);
        jButton22.addActionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jButton00 = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemMostrar = new javax.swing.JMenuItem();
        jMenuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Michi Frame");

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel.setLayout(new java.awt.GridLayout(3, 3));

        jButton00.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton00);

        jButton01.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton01);

        jButton02.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton02);

        jButton10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton10);

        jButton11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton11);

        jButton12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton12);

        jButton20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton20);

        jButton21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton21);

        jButton22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel.add(jButton22);

        jMenuArchivo.setText("Archivo");

        jMenuItemMostrar.setText("Nuevo");
        jMenuItemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemMostrar);

        jMenuBar1.add(jMenuArchivo);

        jMenuAcercaDe.setText("Acerca de");
        jMenuBar1.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarActionPerformed
        matriz = new String[3][3];
        v = cont = 0;
        modificarPanel(1);
    }//GEN-LAST:event_jMenuItemMostrarActionPerformed

    private boolean ganador() {
        boolean b = false;
        if (cont >= 3) {
            for (int i = 0; i < matriz.length && !b; i++) {
                if (matriz[i][0].equals(matriz[i][1]) && matriz[i][1].equals(matriz[i][2])) {
                    b = true;
                    v = 1;
                    s = matriz[i][0];
                }
                if (matriz[0][i].equals(matriz[1][i]) && matriz[1][i].equals(matriz[2][i])) {
                    b = true;
                    v = 1;
                    s = matriz[0][i];
                }
                if (i == 0) {
                    if (matriz[i][i].equals(matriz[i + 1][i + 1]) && matriz[i + 1][i + 1].equals(matriz[i + 2][i + 2])) {
                        b = true;
                        v = 1;
                        s = matriz[i][i];
                    }
                } else if (i == 2) {
                    if (matriz[0][i].equals(matriz[i - 1][i - 1]) && matriz[i - 1][i - 1].equals(matriz[i][0])) {
                        b = true;
                        v = 1;
                        s = matriz[i][i];
                    }
                }
            }
        }
        return b;
    }

    private void modificarPanel(int tipo) {
        Component[] cs = jPanel.getComponents();
        for (int i = 0; i < cs.length; i++) {
            switch (tipo) {
                case 0:
                    cs[i].setEnabled(false);
                    break;
                case 1:
                    cs[i].setEnabled(true);
                    ((javax.swing.JButton) cs[i]).setText("");
                    break;
            }
        }
    }

    public void actionPerformed(ActionEvent e) {
        JButton btn = (JButton) e.getSource();
        String str = "";
        if (cont % 2 == 0) {
            str = "X";
        } else {
            str = "O";
        }
        btn.setText(str);
        btn.setEnabled(false);
        cont++;
        if (e.getSource().equals(jButton00)) {
            matriz[0][0] = str;
        }
        if (e.getSource().equals(jButton01)) {
            matriz[0][1] = str;
        }
        if (e.getSource().equals(jButton02)) {
            matriz[0][2] = str;
        }
        if (e.getSource().equals(jButton10)) {
            matriz[1][0] = str;
        }
        if (e.getSource().equals(jButton11)) {
            matriz[1][1] = str;
        }
        if (e.getSource().equals(jButton12)) {
            matriz[1][2] = str;
        }
        if (e.getSource().equals(jButton20)) {
            matriz[2][0] = str;
        }
        if (e.getSource().equals(jButton21)) {
            matriz[2][1] = str;
        }
        if (e.getSource().equals(jButton22)) {
            matriz[2][2] = str;
        }
        if (ganador() && v == 1) {
            JOptionPane.showMessageDialog(this, "Ganador: " + s, getTitle(), JOptionPane.INFORMATION_MESSAGE);
            modificarPanel(0);
        } else if (cont == 9) {
            JOptionPane.showMessageDialog(this, "No hay Ganador", getTitle(), JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemMostrar;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
